// Mocks generated by Mockito 5.4.4 from annotations
// in hotel_list_app/test/features/hotels/domain/usecases/get_hotels_data_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hotel_list_app/features/hotels/domain/entities/hotels_data.dart'
    as _i2;
import 'package:hotel_list_app/features/hotels/domain/repositories/hotel_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHotelsData_0 extends _i1.SmartFake implements _i2.HotelsData {
  _FakeHotelsData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HotelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHotelRepository extends _i1.Mock implements _i3.HotelRepository {
  MockHotelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HotelsData> getHotelsData({required int? page}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHotelsData,
          [],
          {#page: page},
        ),
        returnValue: _i4.Future<_i2.HotelsData>.value(_FakeHotelsData_0(
          this,
          Invocation.method(
            #getHotelsData,
            [],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.HotelsData>);
}
