// Mocks generated by Mockito 5.4.4 from annotations
// in hotel_list_app/test/features/hotels/domain/repositories/hotel_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hotel_list_app/core/network/api_response.dart' as _i2;
import 'package:hotel_list_app/features/hotels/data/datasources/hotel_local_data_source.dart'
    as _i6;
import 'package:hotel_list_app/features/hotels/data/datasources/hotel_remote_data_source.dart'
    as _i3;
import 'package:hotel_list_app/features/hotels/data/models/hotels_data_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HotelRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHotelRemoteDataSource extends _i1.Mock
    implements _i3.HotelRemoteDataSource {
  MockHotelRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<_i5.HotelsDataModel>> getHotelsData(
          {required int? page}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHotelsData,
          [],
          {#page: page},
        ),
        returnValue: _i4.Future<_i2.ApiResponse<_i5.HotelsDataModel>>.value(
            _FakeApiResponse_0<_i5.HotelsDataModel>(
          this,
          Invocation.method(
            #getHotelsData,
            [],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<_i5.HotelsDataModel>>);
}

/// A class which mocks [HotelLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHotelLocalDataSource extends _i1.Mock
    implements _i6.HotelLocalDataSource {
  MockHotelLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> cacheHotelsData(_i5.HotelsDataModel? hotelsData) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheHotelsData,
          [hotelsData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.HotelsDataModel?> getCachedHotelsData() => (super.noSuchMethod(
        Invocation.method(
          #getCachedHotelsData,
          [],
        ),
        returnValue: _i4.Future<_i5.HotelsDataModel?>.value(),
      ) as _i4.Future<_i5.HotelsDataModel?>);

  @override
  _i4.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
